### ISSUE TITLE
Getting System.PlatformNotSupportedException and Unable to use on .net core Console application

### ISSUE THREAD

**Issue by Vasugupta946** [RickStrahl/Westwind.RazorHosting#42]
Hi, 
I have tried to use both RazorFolderHostContainer and RazorStringHostContainer but it's not working.
I am getting the following error:

Message: Operation is not supported on this platform.
StackTrace: at Microsoft.CSharp.CSharpCodeGenerator.FromFileBatch(CompilerParameters options, String[] fileNames)
   at Microsoft.CSharp.CSharpCodeGenerator.FromDomBatch(CompilerParameters options, CodeCompileUnit[] ea)
   at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromDomBatch(CompilerParameters options, CodeCompileUnit[] ea)
   at System.CodeDom.Compiler.CodeDomProvider.CompileAssemblyFromDom(CompilerParameters options, CodeCompileUnit[] compilationUnits)
   at Westwind.RazorHosting.RazorEngine`1.CompileTemplate(TextReader templateReader, String generatedNamespace, String generatedClassName)
   at Westwind.RazorHosting.RazorEngine`1.CompileTemplate(String templateText, String generatedNamespace, String generatedClassName)
   at Westwind.RazorHosting.RazorFolderHostContainer`1.GetAssemblyFromFileAndCache(String relativePath)
   at Westwind.RazorHosting.RazorFolderHostContainer`1.RenderTemplate(String relativePath, Object model, TextWriter writer, Boolean isLayoutPage)
   
   Does it not support .net core?
   
   Thanks in advance.

**Comment by RickStrahl** [comment]
Library doesn't support .NET Core. Totally different environment so no compatibility.

**Comment by Vasugupta946** [comment]
Thanks for the reply. It will be really helpful if you can put the dependency tag of asp.net in nuget package but if not possible, at the least please mention it in readme.md file. It will be a big help in future for new developers like me.
